name: Create Reports
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  notebooks:
    name: "Generate Reports"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Pull Code
        run: |
          git clone https://github.com/VirtualFlyBrain/VFB_reporting.git
          git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git
          ln -s ../ ./VFB_reporting/VFB_reporting_results

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r VFB_reporting/requirements.txt
          python -m pip install -r VFB_neo4j/requirements.txt
          
      - name: Run query tools test
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          python ./test/query_tools_test.py
          
      - name: Run report runner
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          python ./report_runner.py
  
      - name: Run comparison
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          python ./comparison.py

      - name: Run get catmaid cellTypes
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          python ./get_catmaid_cellTypes.py
          
      - name: Run get catmaid papers
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          python ./get_catmaid_papers.py
          
      - name: Run VFB content report generator
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          python ./VFB_content_report_generator.py

      - name: Create curation files
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/VFB_neo4j/src/
          cd VFB_reporting/src
          rm -vf ../VFB_reporting_results/anat_*.tsv
          rm -vf ../VFB_reporting_results/anat_*.yaml
          ls -lh ../VFB_reporting_results/
          python ./make_curation_records/anat_curation_file_maker.py

      - name: Clean up
        run: |
          rm -rfv VFB_reporting
          rm -rfv VFB_neo4j

      - name: On Completion
        run: |
          git config --global user.email "support@virtualflybrain.org"
          git config --global user.name "gitHub actions"
          git add *
          git add CATMAID_SKID_reports
          git status
          git commit -a -m 'automated report run'

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: support@virtualflybrain.org
          message: 'Automated report run'
          add: '["*.tsv","*.md --force"]'
