name: Generate Release Reports

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to generate report for (optional - if not provided, will process latest tag)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  generate-release-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any required dependencies here
    
    - name: Configure Git
      run: |
        git config --global user.name "VFB Release Bot"
        git config --global user.email "support@virtualflybrain.org"
    
    - name: Generate release report
      run: |
        python scripts/generate_release_report.py
      env:
        TARGET_TAG: ${{ github.event.inputs.tag || github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run cleanup
      run: |
        python scripts/cleanup.py
    
    - name: Commit and push changes
      run: |
        git add releases/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add release report for ${{ github.event.inputs.tag || github.ref_name }}"
          git push origin main
        fi
    
    - name: Push updated tags
      run: |
        git push --tags --force
